### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by anna-kondratiuk** [civicreactor/CareHomeInfo#31]
- on right side
- 2/3 size of screen

**Comment by oecampbell** [comment]
Can you sketch what it's supposed to look like as I can't see the issue please? I've got a huge monitor screen so everything looks fine. Therefore, which screen resolutions does this issue apply to please?

**Comment by juancarloshg** [comment]
I believe when Anna posted this the map wasn't placed correctly in the screen. It is now, so I will close this one.
