### ISSUE TITLE
New Request - MENU - Look at the pic

### ISSUE THREAD

**Issue by anna-kondratiuk** [civicreactor/CareHomeInfo#57]
- The logo should start at this same line like the text on home page starts

- The last page "Feedback" should finish at this same line with map

**Comment by anna-kondratiuk** [comment]
![home page new request]
https://cloud.githubusercontent.com/assets/23171174/21294479/3d1b8a44-c535-11e6-9601-ae0047700a45.png

**Comment by oecampbell** [comment]
I understand visually what you are asking me to do but I honestly don't know how to set it fixed to the responsive grid at this moment of time it could be a media query solution. It's something I will have to revisit later unless one of the lads can figure it out before then.
